name: Publish Packages

on:
  push:
    branches: [ main ]
    paths:
      - 'Directory.Build.props'
      - '.github/workflows/PUBLISH_PACKAGES.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish TaskEndurer
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: TaskEndurer/TaskEndurer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
